# Comment to a new issue.
issueOpened: >
  "The only way to learn a new programming language is by writing programs in it." - Dennis Ritchie

  Thank your for raising a issue. Our team will try to reply you as soon as possible.
  
  “None of us is as smart as all of us.” - Ken Blanchard

pullRequestOpened: >
  "Simplicity is prerequisite for reliability." — Edsger W. Dijkstra
  
  Thank your for raising your pull request. One of us will merge it if everything is ok, otherwise we get in touch with you :smile:
  
  "everybody should learn how to program a computer because it teaches you how to think." - Steve Jobs 


  
