
merge_branch:
  enable: true # Enable merge branch with comment
  branches: ['qa'] # Branches enabled to merge with comment
  users: ['kaduartur', 'victor-schumacher'] # Users enabled to merge with comment
  
issue_project:
  enable: false # Enable issue to project when opening a new issue
  
slack_notification:
  enable: false # Enable slack notification when opening a new pull request
  channel_id: ----
