---
version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jams
      - POSTGRES_USER=jams
      - POSTGRES_PASSWORD=jams
      - MAX_CONNECTIONS=300

