version: '3.3'

services:
  server:
    image: ${BUILD_IMAGE}
    environment:
      TEST_RESULTS_DIR: ${TEST_RESULTS_DIR}
    volumes:
      - .:/home/application
    command: ["/home/application/run-tests-ci.sh"]
    user: root