version: '3.3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jams
      - POSTGRES_USER=jams
      - POSTGRES_PASSWORD=jams