version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./resources/docker-init-db.sql:/docker-entrypoint-initdb.d/docker-init-db.sql
    environment:
      - POSTGRES_DB=jams
      - POSTGRES_USER=jams
      - POSTGRES_PASSWORD=jams