version: 2.1

references:
  images:
    go: &GOLANG_IMAGE cimg/go:1.14
    python: &PYTHON_IMAGE circleci/python:2.7-stretch
    ci_machine: &CI_MACHINE_IMAGE ubuntu-1604:202004-01

  paths:
    test-results: &TEST_RESULTS_DIR bin

  environment: &ENVIRONMENT
    TEST_RESULTS_DIR: *TEST_RESULTS_DIR
    BUILD_IMAGE: *GOLANG_IMAGE

  filters-checks: &FILTERS_CHECK
    branches:
      only:
        - master
        - /^release-.*/
        - /^pull\/.*$/
        - /^feature.*/
        - /^fix.*/

  filters-release: &FILTERS_RELEASE
    branches:
      only:
        - /^release-.*/

executors:
  jams-test-executor:
    machine:
      image: *CI_MACHINE_IMAGE
    working_directory: ~/workspace

  jams-executor:
    docker:
      - image: *GOLANG_IMAGE
        user: root
    working_directory: ~/workspace

  delivery-executor:
    docker:
      - image: *PYTHON_IMAGE
        user: root
    working_directory: /workspace

jobs:
  unit_test:
    executor: jams-test-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Running test
          command: |
            mkdir -p $TEST_RESULTS_DIR
            docker-compose -f docker-compose-ci.yml run server

      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR
      - run:
          name: codecov upload
          when: always
          command: bash <(curl -s https://codecov.io/bash)

  lint:
    executor: jams-test-executor
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            download=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
            wget -O- -q $download |sudo sh -s -- -b /go/bin/ v1.24.0
      - run:
          name: lint
          command: |
            /go/bin/golangci-lint run --no-config --issues-exit-code=0 --deadline=10m -v

  build:
    executor: jams-executor
    branches:
    steps:
      - checkout
      - run:
          name: Running build
          command: |
            make build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR

  docker:
    executor: jams-test-executor
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Creating docker image
          command: |
            . ./helper-ci.sh
            make pack
      - run:
          name: Pushing docker image to registry
          command: |
            . ./helper-ci.sh
            make publish

  release:
    environment:
      <<: *ENVIRONMENT
    executor: delivery-executor
    steps:
      - checkout
      - run:
          name: Releasing
          command: |
            . ./helper-ci.sh
            make release
workflows:
  build-for-requests:
    jobs:
      - lint:
          filters:
            <<: *FILTERS_CHECK
      - unit_test:
          filters:
            <<: *FILTERS_CHECK
      - build:
          filters:
            <<: *FILTERS_RELEASE
          requires:
            - unit_test
            - lint
