CREATE TABLE RIDERS (
  RIDER_ID varchar(50) NOT NULL PRIMARY KEY,
  NAME varchar(100) NOT NULL,
  AGE varchar(10) NOT NULL,
  GENDER varchar(100) NOT NULL,
  CITY varchar(100) NOT NULL,
  CPF varchar(20) NOT NULL,
  PAIDSUBSCRIPTION boolean,
  SPONSORS varchar(200) NOT NULL,
  CATEGORY_ID varchar(100) NOT NULL,
  CREATED TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATED TIMESTAMP WITH TIME ZONE
);
